### ISSUE TITLE
Some warning occured while compiling the programs

### ISSUE THREAD

**Issue by LancerMar** [LancerMar/GuitarTuner#12]
The corresponding bug should be modified according to Warning prompts, improve program robustness @Haotian-Shi-cyber

**Comment by Haotian-Shi-cyber** [comment]
when make, it reports some warning cuz the tuning function hasn't been completed in qt main window, will complete it very soon

**Comment by LancerMar** [comment]
Issues can only be closed after they have been resolved, since issues are used to track bugs

**Comment by LancerMar** [comment]
It`s null function in button click event , It`s already solved by another branch
